package nsbm;


import java.awt.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class StaffPanel extends javax.swing.JPanel {
    Connection conn=null;
    PreparedStatement pst =null;
    ResultSet rs=null;
    
    /**
     * Creates new form StaffPanel
     */
    public StaffPanel() {
        initComponents();
        mainPanel.removeAll();
        updateCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        viewPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        addPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        addStaff = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtstaff_id = new javax.swing.JTextField();
        staffName = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        address = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        desig = new javax.swing.JComboBox<>();
        cmbFac = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        room = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        viewStaff = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        facID = new javax.swing.JTextField();
        txtStaffID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        staff_table = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1090, 830));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewPanelMouseClicked(evt);
            }
        });
        viewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12.png"))); // NOI18N
        viewPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 80, 100));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("View staff");
        viewPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, -1));

        add(viewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 160, 150));

        addPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPanelMouseClicked(evt);
            }
        });
        addPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/10.png"))); // NOI18N
        addPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 100));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Add Staff");
        addPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, -1));

        add(addPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 160, 150));

        lbl1.setBackground(new java.awt.Color(237, 252, 237));
        add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 150));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        addStaff.setBackground(new java.awt.Color(255, 255, 255));
        addStaff.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        addStaff.setPreferredSize(new java.awt.Dimension(1090, 650));
        addStaff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel19.setText("Staff ID");
        addStaff.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 140, 45));

        jLabel20.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel20.setText("Name");
        addStaff.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 140, 45));

        jLabel21.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel21.setText("Faculty ID");
        addStaff.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 140, 40));

        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel22.setText("Gender");
        addStaff.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 140, 45));

        jLabel23.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel23.setText("Address");
        addStaff.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 140, 45));

        jLabel24.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel24.setText("Email");
        addStaff.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 140, 45));

        jLabel29.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel29.setText("Designation");
        addStaff.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 140, 45));

        jLabel25.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel25.setText("Contact no");
        addStaff.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 140, 45));

        txtstaff_id.setFont(new java.awt.Font("Serif", 0, 22)); // NOI18N
        txtstaff_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtstaff_idMouseClicked(evt);
            }
        });
        txtstaff_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstaff_idActionPerformed(evt);
            }
        });
        addStaff.add(txtstaff_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 370, 40));

        staffName.setFont(new java.awt.Font("Serif", 0, 22)); // NOI18N
        addStaff.add(staffName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 370, 40));

        gender.add(male);
        male.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        male.setText("Male");
        addStaff.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 100, 40));

        gender.add(female);
        female.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        female.setText("Female");
        addStaff.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 100, 40));

        address.setFont(new java.awt.Font("Serif", 0, 22)); // NOI18N
        addStaff.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 370, 40));

        email.setFont(new java.awt.Font("Serif", 0, 22)); // NOI18N
        addStaff.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 370, 40));

        contact.setFont(new java.awt.Font("Serif", 0, 22)); // NOI18N
        addStaff.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 370, 40));

        desig.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        desig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecturer", "Senior Lecturer", "Instructor", "Director", "Receptionist", "Network Officer" }));
        addStaff.add(desig, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 370, 40));

        cmbFac.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        cmbFac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        addStaff.add(cmbFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 370, 40));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel13.setText("Delete");
        addStaff.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 610, 70, 30));

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel15.setText("Add");
        addStaff.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 610, 50, 30));

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel16.setText("Update");
        addStaff.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 610, 80, 30));

        btnAdd.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.jpg"))); // NOI18N
        btnAdd.setText("Add ");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        addStaff.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 600, 110, 50));

        btnUpdate.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.jpg"))); // NOI18N
        btnUpdate.setText("Add ");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        addStaff.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, 110, 50));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.jpg"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        addStaff.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 600, 110, 50));

        room.setFont(new java.awt.Font("Serif", 0, 22)); // NOI18N
        addStaff.add(room, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 370, 40));

        jLabel30.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel30.setText("Room No");
        addStaff.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 110, 45));

        lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl.setForeground(new java.awt.Color(255, 0, 0));
        addStaff.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 250, 40));

        mainPanel.add(addStaff, "card2");

        viewStaff.setBackground(new java.awt.Color(255, 255, 255));
        viewStaff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel26.setText("Staff ID");
        viewStaff.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 45));

        jLabel27.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel27.setText("Faculty ID");
        viewStaff.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 100, 45));

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Search");
        viewStaff.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, 70, 30));

        btnSearch.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.jpg"))); // NOI18N
        btnSearch.setText("Add ");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        viewStaff.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 111, 52));

        facID.setFont(new java.awt.Font("Serif", 0, 22)); // NOI18N
        viewStaff.add(facID, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 180, 40));

        txtStaffID.setFont(new java.awt.Font("Serif", 0, 22)); // NOI18N
        viewStaff.add(txtStaffID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 170, 40));

        staff_table.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        staff_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff ID", "Name", "Gender", "Address", "Email", "Contact No", "Designation", "Room No", "Faculty ID"
            }
        ));
        jScrollPane1.setViewportView(staff_table);

        viewStaff.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1090, 580));

        jLabel28.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel28.setText("Name");
        viewStaff.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 80, 45));

        txtName1.setFont(new java.awt.Font("Serif", 0, 22)); // NOI18N
        viewStaff.add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 210, 40));

        mainPanel.add(viewStaff, "card3");

        add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1090, 680));
    }// </editor-fold>//GEN-END:initComponents
    private void updateCombo(){
        String query="select * from faculty";
        try{
            conn=MySqlConnect.ConnectDB();
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next()){
                cmbFac.addItem(rs.getString("faculty_id"));
            }
            conn.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        lbl.setText("");
        if(txtstaff_id.getText().trim().isEmpty()){
            txtstaff_id.setText("**Staff ID number is empty**");
        }
        else if("".equals(staffName.getText()) || "".equals(address.getText()) || "".equals(contact.getText()) || "".equals(email.getText())){
            lbl.setText("Fill the necessary data fiels");
        }
        else{
            String query="insert into staff(staff_id,staff_name,gender,address,email,contact_no,designation,faculty_id,room_no)values(?,?,?,?,?,?,?,?,?)";
            String gender1;


                try{
                    conn=MySqlConnect.ConnectDB();
                    pst=conn.prepareStatement(query);
                    pst.setString(1,txtstaff_id.getText());
                    pst.setString(2,staffName.getText());
                    if(male.isSelected()){
                        gender1="M";
                    }
                    else{
                        gender1="F";
                    }
                    pst.setString(3,gender1);
                    pst.setString(4,address.getText());
                    pst.setString(5,email.getText());
                    pst.setString(6,contact.getText());
                    pst.setString(7, (String) desig.getSelectedItem());
                    pst.setString(8, (String) cmbFac.getSelectedItem());
                    pst.setString(9,room.getText());
                    pst.executeUpdate(); 
                    conn.close();
                    JOptionPane.showMessageDialog(null,"Staff Member added successfully ");
                    clear();
                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(null,e);
                }
            
        }
        
        
        
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void addPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPanelMouseClicked
        mainPanel.removeAll();
        mainPanel.add(addStaff);
        mainPanel.revalidate();
        mainPanel.repaint();
        
        
    }//GEN-LAST:event_addPanelMouseClicked

    private void viewPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPanelMouseClicked
        mainPanel.removeAll();
        mainPanel.add(viewStaff);
        mainPanel.revalidate();
        mainPanel.repaint();
        
    }//GEN-LAST:event_viewPanelMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        String query;
        String a=txtStaffID.getText();
        String b=txtName1.getText();
        String c=facID.getText();
        
        if("".equals(b) && "".equals(c)){
            query="select * from staff where staff_id='"+a+"'";
        }
        else if("".equals(a) && "".equals(c)){
            query="select * from staff where staff_name like '%"+b+"%' order by staff_id asc";
        }
        else{
            query="select * from staff where faculty_id='"+c+"' order by designation desc";
        }
        
        try{
            conn=MySqlConnect.ConnectDB();
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)staff_table.getModel();
            tm.setRowCount(0);
            while(rs.next()){
                Object o[]={rs.getString("staff_id"),rs.getString("staff_name"),rs.getString("gender"),rs.getString("address"),rs.getString("email"),rs.getString("contact_no"),rs.getString("designation"),rs.getString("room_no"),rs.getString("faculty_id")};
                tm.addRow(o);
            }
            conn.close();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(txtstaff_id.getText().trim().isEmpty()){
            txtstaff_id.setText("**Staff ID number is empty**");
        }
        else{
            try{
                conn=MySqlConnect.ConnectDB();
                pst=conn.prepareStatement("select * from staff where staff_id='"+txtstaff_id.getText()+"'");
                rs=pst.executeQuery();
                if(rs.next()){
                    
                    String gender1;

                    String query="update staff set staff_name=?,gender=?,address=?,email=?,contact_no=?,designation=?,faculty_id=?,room_no=? where staff_id=?";

                    try{
                        conn=MySqlConnect.ConnectDB();
                        pst=conn.prepareStatement(query);
                        pst.setString(1, staffName.getText());
                        if(male.isSelected()){
                            gender1="M";
                        }
                        else{
                            gender1="F";
                        }
                        pst.setString(2, gender1);
                        pst.setString(3, address.getText());
                        pst.setString(4, email.getText());
                        pst.setString(5, contact.getText());
                        pst.setString(6, (String) desig.getSelectedItem());
                        pst.setString(7, (String) cmbFac.getSelectedItem());
                        pst.setString(8, room.getText());
                        pst.setString(9,txtstaff_id.getText());
                        pst.executeUpdate();
                        conn.close();
                        JOptionPane.showMessageDialog(null,"Succesfully updated details. ");
                        clear();
                    }
                    catch(SQLException e){
                        JOptionPane.showMessageDialog(null,e);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Staff ID number does not exist.");
                }
            }
            catch(SQLException e){
                   JOptionPane.showMessageDialog(null,e);
            }
        }
        
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtstaff_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstaff_idActionPerformed

        String a=txtstaff_id.getText();
        String query="select * from staff where staff_id='"+a+"'";
        try{
            conn=MySqlConnect.ConnectDB();
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            if(rs.next()){
                staffName.setText(rs.getString("staff_name"));
                String gender1=rs.getString("gender");
                if(gender1.equals("M")){
                    male.setSelected(true);
                }
                else{
                    female.setSelected(true);
                }
                address.setText(rs.getString("address"));
                email.setText(rs.getString("email"));
                contact.setText(rs.getString("contact_no"));
                desig.setSelectedItem(rs.getString("designation"));
                room.setText(rs.getString("room_no"));
                cmbFac.setSelectedItem(rs.getString("faculty_id"));
            }
            else{
                JOptionPane.showMessageDialog(null,"Staff ID does not exist");
            }
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_txtstaff_idActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(txtstaff_id.getText().trim().isEmpty()){
            txtstaff_id.setText("**Staff ID number is empty**");
        }
        else{
            try{
                conn=MySqlConnect.ConnectDB();
                pst=conn.prepareStatement("select * from staff where staff_id='"+txtstaff_id.getText()+"'");
                rs=pst.executeQuery();
                if(rs.next()){
                    int option=JOptionPane.showConfirmDialog(null,"Do you really want to delete Staff member? ","Delete",JOptionPane.YES_NO_OPTION);
                    String query="delete from staff where staff_id=?";
                    if(option==0){
                        try{
                            conn=MySqlConnect.ConnectDB();
                            pst=conn.prepareStatement(query);
                            pst.setString(1, txtstaff_id.getText());
                            pst.execute();
                            conn.close();
                            clear();
                        }
                        catch(SQLException e){
                            JOptionPane.showMessageDialog(null,e);
                        }
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Staff ID number does not exist.");
                }
            }    
            catch(SQLException e){
                   JOptionPane.showMessageDialog(null,e); 
            }
            
        }
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtstaff_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtstaff_idMouseClicked
        txtstaff_id.setText("");
    }//GEN-LAST:event_txtstaff_idMouseClicked
    private void clear(){
        txtstaff_id.setText("");staffName.setText("");gender.clearSelection();address.setText("");
        email.setText("");contact.setText("");room.setText("");cmbFac.setSelectedIndex(0);desig.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPanel;
    private javax.swing.JPanel addStaff;
    private javax.swing.JTextField address;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbFac;
    private javax.swing.JTextField contact;
    private javax.swing.JComboBox<String> desig;
    private javax.swing.JTextField email;
    private javax.swing.JTextField facID;
    private javax.swing.JRadioButton female;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField room;
    private javax.swing.JTextField staffName;
    private javax.swing.JTable staff_table;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtStaffID;
    private javax.swing.JTextField txtstaff_id;
    private javax.swing.JPanel viewPanel;
    private javax.swing.JPanel viewStaff;
    // End of variables declaration//GEN-END:variables
}
